# Generated by Django 5.2 on 2026-05-20 07:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_companyprofile_chat_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='chat_color',
            field=models.CharField(default='#0070f3', help_text='Hex colour for the chat widget.', max_length=7),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='chat_icon',
            field=models.ImageField(blank=True, null=True, upload_to='chat-icons/'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='embed_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='AllowedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Hostname only, no scheme (e.g. acme.com).', max_length=253)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_domains', to='accounts.companyprofile')),
            ],
            options={
                'unique_together': {('company', 'domain')},
            },
        ),
    ]
