# Generated by Django 5.2 on 2026-05-20 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_companyprofile_chat_color_companyprofile_chat_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('conversations_count', models.PositiveIntegerField(default=0)),
                ('documents_count', models.PositiveIntegerField(default=0)),
                ('limit_warning_sent', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_usages', to='accounts.companyprofile')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('company', 'year', 'month')},
            },
        ),
    ]
