# Generated by Django 5.2 on 2026-05-19 19:23

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('txt', 'Text File'), ('text', 'Plain Text'), ('faq', 'FAQ')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='knowledge/')),
                ('raw_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.knowledgedocument')),
            ],
            options={
                'ordering': ['chunk_index'],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
    ]
