# Generated by Django 5.2 on 2026-05-20 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_companyprofile_chat_color_companyprofile_chat_icon_and_more'),
        ('chat', '0003_chatmessage_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('operator_handoff', 'Operator Handoff'), ('unanswered', 'Unanswered Conversation'), ('weekly_summary', 'Weekly Summary')], db_index=True, max_length=20)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='accounts.companyprofile')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='chat.chatsession')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_on_operator_handoff', models.BooleanField(default=True, help_text='Send an email immediately when a session is escalated to a human operator.')),
                ('notify_on_unanswered', models.BooleanField(default=True, help_text='Send an email when a waiting conversation has no operator response for too long.')),
                ('unanswered_threshold_minutes', models.PositiveIntegerField(default=30, help_text='Minutes of silence in a WAITING session before the unanswered email fires.')),
                ('weekly_summary', models.BooleanField(default=True, help_text='Receive a weekly analytics summary every Monday morning.')),
                ('notification_email', models.EmailField(blank=True, help_text="Override the email address that receives notifications. Defaults to the company owner's email when blank.", max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to='accounts.companyprofile')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]
