# Generated by Django 5.2 on 2026-05-20 08:43

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatsession_operator_chatsession_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
